# encoding: utf-8

fixes = {
    "vela": "candle",
    "Vela": "Candle",
    "VELA": "CANDLE",
    "a candle": "o candle",
    "as candles": "os candles",
    "uma candle": "um candle",
    "umas candles": "uns candles",
    "tendência contrária": "contra-tendência",
    "couro cabeludo": "scalp",
    "trocar": "operar",
    "trocam": "operam",
    "trocá-lo": "operá-lo",
    "negociar": "operar",
    "negociá-la": "operá-la",
    "bares": "barras",
    " bar ": " barra ",
    "bars": "barras",
    " Bar ": " Barra ",
    "compasso": "barra",
    "Compasso": "Barra",
    "uns barzinhos": "umas barrinhas",
    "intervalo de negociação": "lateralidade",
    "Intervalo de Negociação": "Lateralidade",
    "Gap de Negociação": "Lateralidade",
    "gap de negociação": "lateralidade",
    "Gaps de Negociação": "Lateralidades",
    "gaps de negociação": "lateralidades",
    "gap de trade": "lateralidade",
    "gap comercial": "lateralidade",
    "gaps de trade": "lateralidades",
    "faixa de negociação": "lateralidade",
    "lateralidade de trade": "lateralidade",
    "lateralidades de trade": "lateralidades",
    "faixa": "lateralidade",
    "um lateralidade": "uma lateralidade",
    "o lateralidade": "a lateralidade",
    "lacuna": "gap",
    "Lacuna": "Gap",
    "intervalo": "gap",
    "Intervalo": "Gap",
    "brecha": "gap",
    "touro": "alta",
    "bull": "alta",
    "bull": "alta",
    "urso": "baixa",
    "bear": "baixa",
    "bois": "comprados",
    "os baixas": "os vendedores",
    "Os baixas": "Os vendedores",
    "os altas": "os compradores",
    "Os altas": "Os compradores",
    "um alta": "uma alta",
    "negociação": "trade",
    "negociaçao": "trade",
    "negócio": "trade",
    "comércio": "trade",
    "uma trade": "um trade",
    "a trade": "o trade",
    "comerciante": "trader",
    "Comerciante": "Trader",
    "negociante": "trader",
    "Negociante": "Trader",
    "cambista": "trader",
    "Cambista": "Trader",
    "negociadores": "traders",
    "Negociadores": "Traders",
    "negociador": "trader",
    "Negociador": "Trader",
    "balanço": "swing",
    "BALANÇO": "SWING",
    "balance": "alongue",
    "inversão": "reversão",
    "inversao": "reversão",
    "reversao": "reversão",
    "recuos": "correções",
    "correçãos": "correções",
    "recuo": "correção",
    "retrocesso": "correção",
    "corre?": "correção",
    "um correção": "uma correção",
    "Um correção": "Uma correção",
    "uns correções": "umas correções",
    "o correção": "a correção",
    "O correção": "A correção",
    "esse correção": "essa correção",
    "aquele correção": "aquela correção",
    "quebra": "rompimento",
    "quebrou": "rompeu",
    "fuga": "rompimento",
    "uma rompimento": "um rompimento",
    "a rompimento": "o rompimento",
    "A rompimento": "O rompimento",
    "as rompimentos": "os rompimentos",
    "rompimentor": "romper",
    "sinalização": "sinal",
    "Sinalização": "Sinal",
    "sinalizador": "sinal",
    "configuração": "setup",
    "configuraçao": "setup",
    "uma setup": "um setup",
    "a setup": "o setup",
    "as setup": "os setup",
    "configurações": "setups",
    "short": "vendido",
    "curta": "vendedora",
    "um curto": "uma venda",
    "um longa": "uma compra",
    "medido": "projetado",
    "'projetado": "'medida",
    "Medido": "Projetado",
    "MEDIDO": "PROJETADO",
    "carrapato": "tick",
    "subida": "alta",
    "baixa mais alta": "mínima mais alta",
    "alta mais baixa": "máxima mais baixa",
    "sua parada": "seu stop",
    "Sua parada": "seu stop",
    "recua": "corrige",
    "negociaçoes": "trades",
    "abaixo da baixa": "abaixo da mínima",
    "acima da alta": "acima da máxima",
    "configuraçoes": "setups",
    "as setups": "os setups",
    "comprar no mercado": "comprar a mercado",
    "vender no mercado": "vender a mercado",
    "uma forte rompimento": "um forte rompimento",
    "pedido de stop": "órdem stop",
    "pedidos de stop": "órdens stop",
    "do aberto": "da abertura",
    "seus longs": "suas compras",
    "seus curtos": "suas vendas",
    "em curto": "vendido",
    "em long": "comprado",
    "seu posto": "sua posição",
    "seus postos": "suas posições",
    "lateralidade de negociação": "lateralidade",
    "lateralidade de trade": "lateralidade",
    "Curto": "Venda",
    "pedidos": "órdens",
    "pedido": "órdem",
    "um pedido": "uma órdem",
    "curto": "vendido",
    "'vendido": "curto",
    "comprado prazo": "longo prazo",
    "vendido prazo": "curto prazo",
    "bermuda": "vendido",
    "Bermuda": "Vendido",
    "calções": "vendas",
    "as setups": "os setups",
    "gap de trade": "lateralidade",
    "troque": "opere",
    "balançar": "alongar",
    "push": "impulso",
    "empurrada": "impulso",
    "apoio": "suporte",
    "negociar": "operar",
    "corrigerá": "corrigirá",
    "suas stops": "seus stops",
    "troca": "operação",
    "negociando": "operando",
    "negociando": "operando",
    "alta medida": "alta projetada",
    "baixa medida": "baixa projetada",
    "ambos os correções": "ambas as correções",
    "envendedorar": "vender",
    "envendidou": "vendeu",
    "vendedora": "venda",
    "o abertura": "a abertura",
    "os aberturas": "as aberturas",
    "ser vendido": "estar vendido",
    "ser comprado": "estar comprado",
    "Dia de Negociação": "Day Trading",
    "dia de negociação": "day trading",
    "olhando para": "buscando",
    "estoques": "ações",
    "estoque": "ação",
    "os órdens": "as órdens",
    "o órdem": "a órdem",
    "negociáveis": "operáveis",
    "negociável": "operável",
    "acompradorar": "comprar",
    "seus órdens": "suas órdens",
    "seu órdem": "sua órdem",
    "negociações": "operações",
    "lateralidade de trade": "lateralidade",
    "curativo": "cuidado",
    "duplo top": "topo duplo",
    "duplo claro": "fundo duplo",
    "inverteu": "reverteu",
    "tres push": "três impulsos",
    "push": "impulso",
    "empurroes": "impulsos",
    "empurrões": "impulsos",
    "empurrao": "impulso",
    "empurrão": "impulso",
    "empurrões": "impulsos",
    "Empurrões": "Impulsos",
    "negocia": "opera",
    "negocie": "opere",
    "negociando": "operando",
    "troca": "opera",
    "dimensionar": "escalar",
    "comercio": "trade",
    "comércio": "trade",
    "COMERCIALIZAR": "OPERAR",
    "comercializável": "operável",
    "CHAPTER": "CAPÍTULO",
    "C H A P T E R": "CAPÍTULO",
    "corriger": "corrigir",
    "imórdens": "impedidos",
    "imórdem": "impedido",
    "m?ma": "mínima",
    "alta 1": "high 1",
    "alto 1": "high 1",
    "alta 2": "high 2",
    "alto 2": "high 2",
    "alta 3": "high 3",
    "alto 3": "high 3",
    "baixa 1": "low 1",
    "baixo 1": "low 1",
    "baixa 2": "low 2",
    "baixo 2": "low 2",
    "baixa 3": "low 3",
    "baixo 3": "low 3",
    " top ": " topo ",
    "o barra": "a barra",
    "os barras": "as barras",
    "O barra": "A barra",
    "Os barras": "As barras",
    "O Barra": "A Barra",
    "Os Barras": "As Barras",
    "uns barras": "umas barras",
    "um barra": "uma barra",
    "preenchido": "executado",
    "preenchida": "executada",
    "preencher": "executar",
    "dois barras": "duas barras",
    "do alta": "de alta",
    "flag": "bandeira",
    "Flag": "Bandeira",
    "o bandeira": "a bandeira",
    "O bandeira": "A bandeira",
    "os correções": "as correções",
    "tendência de contração": "correção de tendência",
    "gaps de medição": "gaps de projeção",
    "gap de medição": "gap de projeção",
    "as setups": "os setups",
    "As setups": "Os setups",
    "a setup": "o setup",
    "A setup": "O setup",
    "invertem": "revertem",
    "a gap": "o gap",
    "A gap": "O gap",
    "envendassem": "vendessem",
    "interrupção": "rompimento",
    "tendência de canal": "canal de tendência",
    "Tendência de Canal": "Canal de Tendência",
    "TENDÊNCIA DE CANAL": "CANAL DE TENDÊNCIA",
    "umo": "um",
    "cinca": "cinco",
    "olhe para": "procure",
    "a lower high": "um alto mais baixo",
    "lower high": "alto mais baixo",
    "uma fundo": "um fundo",
    "a fundo": "o fundo",
    "falhada": "falso",
    "falhado": "falso",
    "ao comprado": "ao longo",
    "seus vendas": "suas vendas",
    "os vendas": "as vendas",
    "seus compras": "suas compras",
    " a opera ": " a operação ",
    "trade lucrativa": "trade lucrativo",
    "à projetado": "à medida",
    "À projetado": "À medida",
    " umo ": " um ",
    " Umo ": " Um ",
    "procompradorado": "prolongado",
    " paro ": " para ",
    "envendando": "vendendo",
    "pico": "rompimento",
    "Pico": "Rompimento",
    "PICO": "ROMPIMENTO",
    "spike": "rompimento",
    "a stop": "o stop",
    "escalpo": "escalpe",
    "parte inferior": "fundo",
    " opera ": " operação ",
    " opera.": " operação.",
    "operaçãoção": "operação",
    "operaçãoções": "operações",
    "operaçãodores": "operadores",
    "operaçãodor": "operador",
    " suo ": " seu ",
    "tendência do baixa": "tendência de baixa",
    " esso ": " esse ",
    "sãa": "são",
    " boo ": " bom ",
    " esto ": " este ",
    ".Esto ": ".Este ",
    " esso ": " esse ",
    ".Esso ": ".Esse ",
    "do baixa": "de baixa",
    " bar,": " barra,",
    " bar.": " barra.",
    "abreviar": "vender",
    "ação do preço": "price action",
    "AÇÃO DO PREÇO": "PRICE ACTION",
    "ação de preço": "price action",
    "AÇÃO DE PREÇO": "PRICE ACTION",
    "açao do preço": "price action",
    "AÇAO DO PREÇO": "PRICE ACTION",
    "açao de preço": "price action",
    "AÇAO DE PREÇO": "PRICE ACTION",
    "rompimentoda": "rompida",
    "canal de baixas": "canal de baixa",
    "uma retirada": "um repique",
    "retirada": "repique",
    "baixas fortes": "vendedores fortes",
    "reduzir": "vender",
    "oscilações": "movimentos",
    "oscilação": "movimento",
    "PADRÕES DE TENDÊNCIAS COMUNS": "PADRÕES COMUNS DE TENDÊNCIA",
    "seus comprados": "suas compras",
    "procompradorada": "prolongada",
    "procompradorado": "prolongado",
    "'abertura": "'aberto",
    "tendência de baixas": "tendência de baixa",
    " coma ": " como ",
    "prazo": "tempo",
    "dia de tendência de trade": "tendência em dia lateral",
    "dias de tendência de trade": "Tendência em Dias Laterais",
    "Trending Days de Faixa de Negociação ": "Tendência em Dias Laterais",
    "Tendência dos Dias da Faixa de Negociação ": "Tendência em Dias Laterais",
    "dia de lateralidade de tendência": "tendência em dia lateral",
    "Dia de Lateralidade de Tendência": "Tendência em Dia Lateral",
    "dias de lateralidade de tendência": "tendência em dias laterais",
    "Dias de Lateralidade de Tendência": "Tendência em Dias Laterais",
    "TRENDING DIES DA FAIXA DE NEGOCIAÇÃO": "TENDÊNCIA EM DIAS LATERAIS",
    "Tendências de trade": "Tendência em dia lateral",
    "'sestops": "'separadas",
    "bandeira de baixas": "bandeira de baixa",
    "bandeiras de baixas": "bandeiras de baixa",
    "seus vendidos": "suas vendas",
    "suas vendidos": "suas vendas",
    "da repique": "do repique",
    "esaltau": "estourou",
    "esaltau": "estourou",
    "abaixo de sua baixa": "abaixo de sua mínima",
    "acima de sua alta": "acima de sua máxima",
    "amínima": "abaixo",
    "tendência de máxima": "tendência de alta",
    "canal de máxima": "canal de alta",
    "pernada de máxima": "pernada de alta",
    "reversão de máxima": "reversão de alta",
    "corpo de máxima": "corpo de alta",
    "bandeira de máxima": "bandeira de alta",
    "tendência de mínima": "tendência de baixa",
    "canal de mínima": "canal de baixa",
    "pernada de mínima": "pernada de baixa",
    "reversão de mínima": "reversão de baixa",
    "corpo de mínima": "corpo de baixa",
    "bandeira de mínima": "bandeira de baixa",
    "olhar para": "procurar",
    "barra externo": "barra externa",
    "baixas": "baixa",
    "corpo de boi": "corpo de alta",
    "quatra barras": "quatro barras",
    "barra de dentro": "barra interna",
    "do baixa": "de baixa",
    "'sestops": "'separadas",
    "as gaps": "os gaps",
    "As gaps": "Os gaps",
    "barra de suporte": "barra de baixa",
    "baixa de baixa": "baixa da mínima",
    "tendência de suportar": "tendência de baixa",
    "tendência forte de suportar": "tendência forte de baixa",
    "traders do dia": "day traders",
    "trader do dia": "day trader",
    "seu alto": "sua máxima",
    "barra de desagregação": "barra de rompimento",
    "barra de rompimento": "barra de rompimento",
    "ruptura": "rompimento",
    "desagregação": "rompimento",
    "parados": "estopados",
    "recuperação": "reversão",
    "compram nos altos": "compram nas máximas",
    "vendem nos baixos": "vendem nas mínimas",
    "folga": "gap",
    "do aberto do dia": "da abertura do dia",
    "pequeno dia de tendência de retração": "dia de tendência de retração pequena",
    "pequeno dia de tendência de correção": "dia de tendência de correção pequena",
}
