# encoding: utf-8

correcoes ={
    "tendência contrária": "contra-tendência",
    "couro cabeludo": "scalp",
    "trocar": "operar",
    "negociar": "operar",
    "bares": "barras",
    "lacuna": "gap",
    "intervalo de negociação": "lateralidade",
    "intervalo": "gap",
    "faixa de negociação": "lateralidade",
    "touro": "alta",
    "bull": "alta",
    "urso": "baixa",
    "bear": "baixa",
    "negociação": "trade",
    "negócio": "trade",
    "comerciante": "trader",
    "cambista": "trader",
    "balanço": "swing",
    "inversão": "reversão",
    "recuo": "correção",
    "quebra": "rompimento",
    "fuga": "rompimento",
    "sinalização": "sinal",
    "configuração": "setup",
    "configurações": "setups",
    "longo": "comprado",
    "short": "vendido",
    "medido": "projetado",
}
